'use client';

import { useState } from 'react';
import { Loader2, Download, Code, Database, Globe, CheckCircle, AlertCircle } from 'lucide-react';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import CodePreview from '@/components/CodePreview';

interface CloneResult {
  html: string;
  css: string;
  sqlSchema: string;
  nodeRoute: string;
  metadata: {
    sourceUrl: string;
    processingTime: string;
    timestamp: string;
  };
}

export default function Home() {
  const [url, setUrl] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<CloneResult | null>(null);
  const [error, setError] = useState('');
  const [activeTab, setActiveTab] = useState<'preview' | 'html' | 'css' | 'sql' | 'node'>('preview');
  const [previewMode, setPreviewMode] = useState<'desktop' | 'mobile' | 'responsive'>('responsive');

  const handleClone = async () => {
    if (!url.trim()) {
      setError('Please enter a valid URL');
      return;
    }

    setLoading(true);
    setError('');
    setResult(null);

    try {
      const response = await fetch('http://localhost:5000/api/clone', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ url }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.message || 'Failed to clone website');
      }

      if (data.success && data.data) {
        setResult(data.data);
        setActiveTab('preview');
      } else {
        throw new Error('Invalid response from server');
      }
    } catch (err: any) {
      setError(err.message || 'An error occurred while cloning the website');
      console.error('Clone error:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async () => {
    if (!result) return;

    try {
      const zip = new JSZip();

      // Create index.html with embedded CSS
      const fullHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cloned Website</title>
  <style>
${result.css}
  </style>
</head>
<body>
${result.html}
</body>
</html>`;

      zip.file('index.html', fullHTML);
      zip.file('styles.css', result.css);
      zip.file('schema.sql', result.sqlSchema);
      zip.file('server.js', result.nodeRoute);

      // Add README
      const readme = `# Cloned Website

Source: ${result.metadata.sourceUrl}
Generated: ${new Date(result.metadata.timestamp).toLocaleString()}
Processing Time: ${result.metadata.processingTime}

## Files Included

- **index.html**: The cloned webpage with embedded CSS
- **styles.css**: Extracted CSS styles
- **schema.sql**: PostgreSQL database schema
- **server.js**: Node.js Express routes for CRUD operations

## Setup Instructions

### Frontend
1. Open index.html in your browser

### Backend
1. Install PostgreSQL
2. Run schema.sql to create database tables
3. Install Node.js dependencies: npm install express pg
4. Configure database connection in server.js
5. Run: node server.js

Generated by WebCloneAI
`;

      zip.file('README.md', readme);

      // Generate and download zip
      const content = await zip.generateAsync({ type: 'blob' });
      const fileName = `webclone-${Date.now()}.zip`;
      saveAs(content, fileName);

      console.log('Download completed:', fileName);
    } catch (err) {
      console.error('Download error:', err);
      setError('Failed to create download package');
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-black text-white">
      {/* Header */}
      <header className="border-b border-gray-700 bg-gray-900/50 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="bg-gradient-to-r from-blue-500 to-purple-600 p-2 rounded-lg">
                <Code className="w-6 h-6" />
              </div>
              <div>
                <h1 className="text-2xl font-bold bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
                  WebCloneAI
                </h1>
                <p className="text-xs text-gray-400">AI-Powered Web Cloning Tool</p>
              </div>
            </div>
            <div className="flex items-center space-x-2 text-sm text-gray-400">
              <Globe className="w-4 h-4" />
              <span>Stateless Architecture</span>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="container mx-auto px-4 py-8">
        {/* Input Section */}
        <div className="max-w-4xl mx-auto mb-8">
          <div className="bg-gray-800 rounded-xl p-6 shadow-2xl border border-gray-700">
            <h2 className="text-xl font-semibold mb-4 flex items-center">
              <Globe className="w-5 h-5 mr-2 text-blue-400" />
              Enter Website URL
            </h2>
            
            <div className="flex gap-3">
              <input
                type="url"
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                onKeyPress={(e) => e.key === 'Enter' && handleClone()}
                placeholder="https://example.com"
                disabled={loading}
                className="flex-1 px-4 py-3 bg-gray-900 border border-gray-600 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent disabled:opacity-50 disabled:cursor-not-allowed"
              />
              <button
                onClick={handleClone}
                disabled={loading || !url.trim()}
                className="px-6 py-3 bg-gradient-to-r from-blue-600 to-purple-600 rounded-lg font-semibold hover:from-blue-700 hover:to-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all flex items-center space-x-2 min-w-[120px] justify-center"
              >
                {loading ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    <span>Cloning...</span>
                  </>
                ) : (
                  <>
                    <Code className="w-5 h-5" />
                    <span>Clone</span>
                  </>
                )}
              </button>
            </div>

            {error && (
              <div className="mt-4 p-4 bg-red-900/30 border border-red-700 rounded-lg flex items-start space-x-2">
                <AlertCircle className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" />
                <p className="text-red-300 text-sm">{error}</p>
              </div>
            )}

            {loading && (
              <div className="mt-4 space-y-2">
                <div className="flex items-center space-x-2 text-sm text-gray-400">
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>Scraping website...</span>
                </div>
                <div className="w-full bg-gray-700 rounded-full h-2 overflow-hidden">
                  <div className="h-full bg-gradient-to-r from-blue-500 to-purple-500 animate-pulse"></div>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Results Section */}
        {result && (
          <div className="max-w-7xl mx-auto">
            {/* Metadata Card */}
            <div className="bg-gray-800 rounded-xl p-4 mb-4 border border-gray-700 flex items-center justify-between">
              <div className="flex items-center space-x-6 text-sm">
                <div className="flex items-center space-x-2">
                  <CheckCircle className="w-4 h-4 text-green-400" />
                  <span className="text-gray-300">Clone Successful</span>
                </div>
                <div className="text-gray-400">
                  <span className="font-semibold">Time:</span> {result.metadata.processingTime}
                </div>
                <div className="text-gray-400 truncate max-w-md">
                  <span className="font-semibold">Source:</span> {result.metadata.sourceUrl}
                </div>
              </div>
              <button
                onClick={handleDownload}
                className="px-4 py-2 bg-green-600 rounded-lg font-semibold hover:bg-green-700 transition-all flex items-center space-x-2"
              >
                <Download className="w-4 h-4" />
                <span>Download ZIP</span>
              </button>
            </div>

            {/* Tabs */}
            <div className="bg-gray-800 rounded-t-xl border-b border-gray-700">
              <div className="flex space-x-1 p-2">
                {[
                  { id: 'preview' as const, label: 'Preview', icon: Globe },
                  { id: 'html' as const, label: 'HTML', icon: Code },
                  { id: 'css' as const, label: 'CSS', icon: Code },
                  { id: 'sql' as const, label: 'SQL Schema', icon: Database },
                  { id: 'node' as const, label: 'Node.js Route', icon: Code },
                ].map((tab) => (
                  <button
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id)}
                    className={`flex items-center space-x-2 px-4 py-2 rounded-lg transition-all ${
                      activeTab === tab.id
                        ? 'bg-gray-700 text-white'
                        : 'text-gray-400 hover:text-white hover:bg-gray-700/50'
                    }`}
                  >
                    <tab.icon className="w-4 h-4" />
                    <span className="text-sm font-medium">{tab.label}</span>
                  </button>
                ))}
              </div>
            </div>

            {/* Content Area */}
            <div className="bg-gray-800 rounded-b-xl border border-gray-700 border-t-0">
              {activeTab === 'preview' && (
                <div className="p-4">
                  {/* Device Preview Controls */}
                  <div className="flex items-center justify-center gap-2 mb-4">
                    <button
                      onClick={() => setPreviewMode('desktop')}
                      className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${
                        previewMode === 'desktop'
                          ? 'bg-blue-600 text-white'
                          : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
                      }`}
                    >
                      🖥️ Desktop
                    </button>
                    <button
                      onClick={() => setPreviewMode('mobile')}
                      className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${
                        previewMode === 'mobile'
                          ? 'bg-blue-600 text-white'
                          : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
                      }`}
                    >
                      📱 Mobile
                    </button>
                    <button
                      onClick={() => setPreviewMode('responsive')}
                      className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${
                        previewMode === 'responsive'
                          ? 'bg-blue-600 text-white'
                          : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
                      }`}
                    >
                      ↔️ Responsive
                    </button>
                  </div>

                  {/* Preview Container */}
                  <div className="bg-gray-900 rounded-lg p-4 flex justify-center">
                    <div
                      className={`bg-white rounded-lg overflow-hidden shadow-2xl transition-all duration-300 ${
                        previewMode === 'desktop'
                          ? 'w-full'
                          : previewMode === 'mobile'
                          ? 'w-[375px]'
                          : 'w-full resize'
                      }`}
                      style={{ 
                        height: '600px',
                        resize: previewMode === 'responsive' ? 'both' : 'none',
                        overflow: 'auto'
                      }}
                    >
                      <iframe
                        srcDoc={result.html.includes('<!DOCTYPE html>') 
                          ? result.html 
                          : `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
  <title>Preview</title>
  <style>
    /* Reset and base styles */
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif;
      line-height: 1.6;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
    }
    img {
      max-width: 100%;
      height: auto;
    }
    /* Injected CSS */
    ${result.css}
  </style>
</head>
<body>
${result.html}
</body>
</html>`}
                        className="w-full h-full border-0"
                        title="Preview"
                        sandbox="allow-same-origin allow-scripts allow-popups allow-forms"
                      />
                    </div>
                  </div>
                  
                  <div className="text-center text-gray-400 text-sm mt-2">
                    {previewMode === 'responsive' && '💡 Drag the corner to resize the preview'}
                    {previewMode === 'mobile' && '📱 Viewing in mobile size (375px)'}
                    {previewMode === 'desktop' && '🖥️ Viewing in desktop size (100%)'}
                  </div>
                </div>
              )}

              {activeTab === 'html' && (
                <CodePreview code={result.html} language="html" />
              )}

              {activeTab === 'css' && (
                <CodePreview code={result.css} language="css" />
              )}

              {activeTab === 'sql' && (
                <CodePreview code={result.sqlSchema} language="sql" />
              )}

              {activeTab === 'node' && (
                <CodePreview code={result.nodeRoute} language="javascript" />
              )}
            </div>
          </div>
        )}

        {/* Features Section */}
        {!result && !loading && (
          <div className="max-w-4xl mx-auto mt-12">
            <div className="grid md:grid-cols-3 gap-6">
              <div className="bg-gray-800 p-6 rounded-xl border border-gray-700">
                <Globe className="w-10 h-10 text-blue-400 mb-3" />
                <h3 className="text-lg font-semibold mb-2">Web Scraping</h3>
                <p className="text-gray-400 text-sm">
                  Extract clean HTML and CSS from any website using Puppeteer
                </p>
              </div>
              <div className="bg-gray-800 p-6 rounded-xl border border-gray-700">
                <Database className="w-10 h-10 text-purple-400 mb-3" />
                <h3 className="text-lg font-semibold mb-2">AI Code Generation</h3>
                <p className="text-gray-400 text-sm">
                  Generate PostgreSQL schemas and Express routes using OpenAI
                </p>
              </div>
              <div className="bg-gray-800 p-6 rounded-xl border border-gray-700">
                <Download className="w-10 h-10 text-green-400 mb-3" />
                <h3 className="text-lg font-semibold mb-2">Instant Download</h3>
                <p className="text-gray-400 text-sm">
                  Download all generated files as a ZIP package instantly
                </p>
              </div>
            </div>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-700 bg-gray-900/50 mt-12">
        <div className="container mx-auto px-4 py-6 text-center text-gray-400 text-sm">
          <p>WebCloneAI © 2025 | Stateless Web Cloning Tool | Powered by OpenAI & Puppeteer</p>
        </div>
      </footer>
    </div>
  );
}
